### ISSUE TITLE
Ne pas préremplir ID

### ISSUE THREAD

**Issue by jfpace** [AriiPortal/CoreBundle#11]
Bonjour,
Au login, le préremplissage en grisé du nom d'utilisateur (operator) est souvent un facteur d'erreur.
On a tendance à ne pas le modifier en pensant que le champs est rempli alors que l'id n'est pas saisie.
Serait-il possible de mentionner "Tapez ici operator" ?
ou rien ?

cldt

jf

**Comment by AriiPortal** [comment]
Peu explicite pour une demo mais inutile pour une version définitive où chacun dispose de son compte. 
A supprimer totalement et remplir par le compte qui pourra être précisé dans l'url d'appel.

[--- Commented from Asana.com
#commenter Eric Angenault
---[aa]

**Comment by AriiPortal** [comment]
Corrigé dans le module UserBundle.
