### ISSUE TITLE
Menu non affiché

### ISSUE THREAD

**Issue by jfpace** [AriiPortal/CoreBundle#14]
La dernière mise à jour des modules corebundle, jidbundle et jocbundle visant à utilser le role 'READER'  a modiifié le comportememnt du menu, seuls sont affichés les modules "suivi" et "administration" si on est connecté en "administrator" et "suivi" si on est en operator. 
![capture d ecran 2016-11-22 a 13 05 31](https://cloud.githubusercontent.com/assets/17028741/20523262/7e4253da-b0b4-11e6-90ae-8cff3c2c8943.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/38933038835937/224288581557957)

**Comment by AriiPortal** [comment]
Bonjour,

Plusieurs choses à considérer:

1) Comme indiqué dans l'article http://wiki.sos-paris.com/index.php/Cr%C3%A9er_un_compte_en_lecture_seule
Le rôle READER n'existe pas car le USER est en soi un utilisateur connecté mais sans droit.

2) Le menu et plus généralement les modules dépendent en premier lieu du rôle de l'utilisateur, cette configuration est dans le fichier parameters.yml:
```
arii_core:
    modules: 'JID(ROLE_USER),DS(ROLE_USER),JOC(ROLE_USER),MFT(ROLE_USER),GVZ(ROLE_USER),Report(ROLE_USER),JOE(ROLE_BUILDER),Blockly(ROLE_BUILDER),Admin(ROLE_ADMIN)'

```

3) Ces rôles dépendent de la hiérarchie définie dans le fichier security.yml:
```
    role_hierarchy:
        ROLE_ADMIN:       [ROLE_SYSADMIN,ROLE_OPERATOR,ROLE_DEVELOPPER]
        ROLE_MANAGER:     [ROLE_USER,ROLE_OPERATOR,ROLE_DEVELOPPER]
        ROLE_OPERATOR:    [ROLE_USER]
        ROLE_DEVELOPPER:  [ROLE_USER]       
        ROLE_SYSADMIN:    [ROLE_ALLOWED_TO_SWITCH,ROLE_DEVELOPPER]
```

4) Les paramètres du fichier parameters.yml vons disparaitre au profit de la table arii_parameter qui sera éditée par le module admin. Cette table se remplit actuellement en fonction du fichier parameters.yml pour être populée lorsque les paramètres du fichier seront supprimés. 

Bonne journée, 
Eric

**Comment by AriiPortal** [comment]
La notion de variable dans les parametres et/ou dans la base de données semble perturbantes. La nouvelle version intègre directement une configuration par défaut:
* le fichier parameters.yml ne contient plus que les paramètres de connexion AriiDB
* si les tables sont vides, elles sont automatiquement remplies avec les valeurs standard
* le module admin permet de modifier ces paramètres à posteriori
