### ISSUE TITLE
descriptions des modules en anglais

### ISSUE THREAD

**Issue by AxelANGENAULT** [AriiPortal/CoreBundle#4]
Les descriptions des modules ne semblent pas exister en anglais :
- Les descriptions courtes renvoient : summary.* (i.e. summary.JID )
- Les descriptions longues renvoient : text.*  (i.e. text.DS )
De plus le DSBundle est appelé "module.DS", le terme Schedule serait plus approprié.

![arii_en](https://cloud.githubusercontent.com/assets/11269587/12420548/9f6d653e-bebd-11e5-8855-51f5650c1497.png)
[output_find:"summaryJID".txt](https://github.com/AriiPortal/CoreBundle/files/95975/output_find.summaryJID.txt)
[output_find:"textJID".txt](https://github.com/AriiPortal/CoreBundle/files/95976/output_find.textJID.txt)

**Comment by AriiPortal** [comment]
Ces traductions sont à remplir dans les fichiers de traduction de chaque module.

**Comment by AxelANGENAULT** [comment]
Je prend cette tâche. 
J'ai déjà édité dans message.en.yml `module.DS: Schedule`

Ça fonctionne pour la navigation
![schedule_ar](https://cloud.githubusercontent.com/assets/11269587/12453221/8cb6e8f4-bf92-11e5-81c5-3e06bf9174ab.png)
![schedule_ari](https://cloud.githubusercontent.com/assets/11269587/12453223/8f33c430-bf92-11e5-8c53-f4b1c79b7349.png)

Mais pas pour ça :
![plan_arii](https://cloud.githubusercontent.com/assets/11269587/12453287/df4cf7a2-bf92-11e5-8cee-deb5d13bf21e.png)

C'est écrie en dans
`Symfony/src/Arii/DSBundle/Resources/views/Default/ribbon.json.twig`:
` text:"{{ "Plan" | trans }}",`

Cette clef n'existait ni dans `message.fr`, ni dans `message.en`, je l'ai ajouté  : 
![plan_arii](https://cloud.githubusercontent.com/assets/11269587/12453563/0cacaa52-bf94-11e5-9885-04200aefa709.png)

Il aurait peut-être mieux valu changer l'appel pour `module.DS` ?

**Comment by AriiPortal** [comment]
Toute modification de ce type doit passer une purge du cache (suppression des fichiers app/cache).

**Comment by AxelANGENAULT** [comment]
Je supprime toujours les caches.

Je pense que vous vous êtes trompé, ce ticket est clos résolu (je m'occupe de remplir les trous  :smirk:),
l'autre ticket (https://github.com/AriiPortal/Arii/issues/2#event-519336557) aurais pu être dû aux caches, mais non :disappointed:.

**Comment by AriiPortal** [comment]
????
